Models/Complaint.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.Build.Construction;
namespace HousingSystem.Models;

public class Complaint{
    [Key]
    [Column(TypeName = "varchar(36)")]
    public string ComplaintId{get; set; } 
    [Required]
    public string ComplaintGiver{get; set; }
    [Required]
    [DataType(DataType.Date)]
    public DateTime DateOfComplaint{get ; set; } 
    [Required]
    public string ComplaintTitle{get ; set; }
    [Required]
    public string ComplaintCategory{get ; set;}
    [Required]
    public string ComplaintDetail{get ; set; }

    
}

Controllers/ComplaintController.cs
using Microsoft.AspNetCore.Mvc;
using HousingSystem.Data;
using HousingSystem.Models;
namespace HousingSystem.Controllers;
public class ComplaintController:Controller{
    private readonly ApplicationDbContext _db;

    public ComplaintController(ApplicationDbContext db)
{
    _db = db;
}

public IActionResult Index()
{
     IEnumerable<Complaint> objComplaintList = _db.Complaint;
        return View(objComplaintList);
}

//GET
    public IActionResult Create()
    {   
       var userFName = HttpContext.Session.GetString("UserFName");
       var userLName = HttpContext.Session.GetString("UserLName");
       Console.WriteLine($"UserFName: {userFName}, UserLName: {userLName}");
       if(userFName == null || userLName == null ){
        return RedirectToAction("Verify", "User");
       }
       ViewBag.ComplaintGiver = $"{userFName} {userLName}";

      
       var model = new Complaint
    {
        ComplaintGiver = ViewBag.ComplaintGiver,
        ComplaintId = Guid.NewGuid().ToString()
    };
        return View(model);
    }

     
  [HttpPost]
[ValidateAntiForgeryToken]
public IActionResult Create(Complaint obj)
{   var userFName = HttpContext.Session.GetString("UserFName");
    var userLName = HttpContext.Session.GetString("UserLName");

    ViewBag.ComplaintGiver = $"{userFName} {userLName}";

    // Always set ComplaintGiver
    Console.WriteLine($"ViewBag.ComplaintGiver: {ViewBag.ComplaintGiver}");
obj.ComplaintGiver = ViewBag.ComplaintGiver;

    obj.ComplaintGiver = ViewBag.ComplaintGiver;

    if (ModelState.IsValid && obj.DateOfComplaint >= DateTime.Today.AddDays(-30) && obj.DateOfComplaint <= DateTime.Today)
    {
        obj.ComplaintId = Guid.NewGuid().ToString();
        _db.Complaint.Add(obj);
        _db.SaveChanges();
        TempData["success"] = "Complaint is registered";
        return RedirectToAction("Index");
    }

    // If ModelState is not valid or date conditions are not met, return to the view
    return View(obj);
}

//GET
    public IActionResult Edit(string ComplaintId)
    {    Console.WriteLine("Edit action is being hit!");
        var userFName = HttpContext.Session.GetString("UserFName");
       var userLName = HttpContext.Session.GetString("UserLName");
        if(userFName == null || userLName == null ){
        return RedirectToAction("Verify", "User");
       }
       if(ComplaintId == null){
        Console.WriteLine(ComplaintId);
        return NotFound();
       }  
       var ComplaintFromDb = _db.Complaint.Find(ComplaintId);
       if(ComplaintFromDb == null){
        return NotFound();
       }
        return View(ComplaintFromDb);
    }

    //POST
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Edit(Complaint obj)
    {  
        if(ModelState.IsValid)
    {
       _db.Complaint.Update(obj);
       _db.SaveChanges();
       TempData["success"]="Complaint is updated";
        return RedirectToAction("Index");
        
    }
    return View(obj);
    }

    //GET
    public IActionResult Delete(string ComplaintId)
    {   var userFName = HttpContext.Session.GetString("UserFName");
       var userLName = HttpContext.Session.GetString("UserLName");
        if(userFName == null || userLName == null ){
        return RedirectToAction("Verify", "User");
       }
       if(ComplaintId == null){
        return NotFound();
       }  
       var ComplaintFromDb = _db.Complaint.Find(ComplaintId);
       if(ComplaintFromDb == null){
        return NotFound();
       }
        return View(ComplaintFromDb);
    }

    //POST
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult DeletePost(string ComplaintId)
    {   var obj = _db.Complaint.Find(ComplaintId);
        if(obj == null){
            return NotFound();
        }
    
       _db.Complaint.Remove(obj);
       _db.SaveChanges();
       TempData["success"]="Complaint is deleted";
        return RedirectToAction("Index");
    
    
    }
    
    


 public IActionResult View(string ComplaintId)
    {    Console.WriteLine("Edit action is being hit!");
    var userFName = HttpContext.Session.GetString("UserFName");
       var userLName = HttpContext.Session.GetString("UserLName");
        if(userFName == null || userLName == null ){
        return RedirectToAction("Verify", "User");
       }
       if(ComplaintId == null){
        Console.WriteLine(ComplaintId);
        return NotFound();
       }  
       var ComplaintFromDb = _db.Complaint.Find(ComplaintId);
       if(ComplaintFromDb == null){
        return NotFound();
       }
        return View(ComplaintFromDb);
    }
}

Views/Complaint/Create.cshtml
@model Complaint



<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Create Complaint</h2>
            <hr/>
            </div>
            <div asp-validation-summary="All"></div>
            <div class="mb-3">
                <label asp-for="ComplaintId"></label>
                <input asp-for="ComplaintId" class="form-control" disabled />
                <input type="hidden" asp-for="ComplaintId" />

                <label>Complaint registered by</label>
                <input asp-for="ComplaintGiver" class="form-control" disabled />
                <input type="hidden" asp-for="ComplaintGiver" />

                <label asp-for="DateOfComplaint"></label>
                <input asp-for="DateOfComplaint" class="form-control"/>
                <span asp-validation-for="DateOfComplaint" class="text-danger"></span>
                <label asp-for="ComplaintTitle"></label>
               <input asp-for="ComplaintTitle" class="form-control" />


                <span asp-validation-for="ComplaintTitle" class="text-danger"></span>
                <label asp-for="ComplaintCategory"></label>
                <select asp-for="ComplaintCategory" class="form-control">
                 <option asp-for="ComplaintCategory" value="Water Issue">Water Issue</option>
                 <option asp-for="ComplaintCategory" value="Bore Well Issue">Bore Well Issue</option>
                 <option asp-for="ComplaintCategory" value="Neighbor Issue">Neighbor Issue</option>
                 <option asp-for="ComplaintCategory" value="Electricity Issue">Electricity Issue</option>
                 <option asp-for="ComplaintCategory" value="Lift Issue">Lift Issue</option>
                 <option asp-for="ComplaintCategory" value="Parking Issue">Parking Issue</option>
                 <option asp-for="ComplaintCategory" value="Vehicle Damage Issue">Vehicle Damage Issue</option>
                 <option asp-for="ComplaintCategory" value="Stolen/Theft Issue">Stolen/Theft Issue</option>
                 <option asp-for="ComplaintCategory" value="Noise Issue">Noise Issue</option>
                 <option asp-for="ComplaintCategory" value="Other Issue">Other Issue</option>
                </select>
                <span asp-validation-for="ComplaintCategory" class="text-danger"></span>
                <label asp-for="ComplaintDetail"></label>
                
                    <textarea asp-for="ComplaintDetail">
                        
                    </textarea>
                    
                <span asp-validation-for="ComplaintDetail" class="text-danger"></span>
               
               
               

            </div>
    
    <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
    <a asp-controller="Complaint" asp-action="Index" class="btn btn-secondary" style="width:150px">
        Back to list
    </a>
    </div>
</form>
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial"></partial>
    }
}

Views/Complaint/Delete.cshtml
@model Complaint



<form method="post" asp-action="DeletePost">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Delete Complaint</h2>
            <hr/>
            </div>
            <div asp-validation-summary="All"></div>
            <div class="mb-3">
                <label asp-for="ComplaintId"></label>
                <input asp-for="ComplaintId" class="form-control" disabled/>
                <input asp-for="ComplaintId" class="form-control" hidden/>
                <span asp-validation-for="ComplaintId" class="text-danger"></span>
                <label asp-for="DateOfComplaint"></label>
                <input asp-for="DateOfComplaint" class="form-control"/>
                <span asp-validation-for="DateOfComplaint" class="text-danger"></span>
                <label asp-for="ComplaintGiver"></label>
                <input asp-for="ComplaintGiver" class="form-control"/>
                <span asp-validation-for="ComplaintGiver" class="text-danger"></span>
                <label asp-for="ComplaintTitle"></label>
               <input asp-for="ComplaintTitle" class="form-control" />


                <span asp-validation-for="ComplaintTitle" class="text-danger"></span>
                <label asp-for="ComplaintCategory"></label>
                <select asp-for="ComplaintCategory" class="form-control">
                 <option asp-for="ComplaintCategory" value="Water Issue">Water Issue</option>
                 <option asp-for="ComplaintCategory" value="Bore Well Issue">Bore Well Issue</option>
                 <option asp-for="ComplaintCategory" value="Neighbor Issue">Neighbor Issue</option>
                 <option asp-for="ComplaintCategory" value="Electricity Issue">Electricity Issue</option>
                 <option asp-for="ComplaintCategory" value="Lift Issue">Lift Issue</option>
                 <option asp-for="ComplaintCategory" value="Parking Issue">Parking Issue</option>
                 <option asp-for="ComplaintCategory" value="Vehicle Damage Issue">Vehicle Damage Issue</option>
                 <option asp-for="ComplaintCategory" value="Stolen/Theft Issue">Stolen/Theft Issue</option>
                 <option asp-for="ComplaintCategory" value="Noise Issue">Noise Issue</option>
                 <option asp-for="ComplaintCategory" value="Other Issue">Other Issue</option>
                </select>
                <span asp-validation-for="ComplaintCategory" class="text-danger"></span>
                <label asp-for="ComplaintDetail"></label>
                
                    <textarea asp-for="ComplaintDetail"></textarea>
                    
                <span asp-validation-for="ComplaintDetail" class="text-danger"></span>
               
               
               

            </div>
    
    <button type="submit" class="btn btn-primary" style="width:150px">Delete</button>
    <a asp-controller="Complaint" asp-action="Index" class="btn btn-secondary" style="width:150px">
        Back to list
    </a>
    </div>
</form>
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial"></partial>
    }
}

Views/Complaint/Edit.cshtml
@model Complaint



<form method="post" asp-action="Edit">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Edit Complaint</h2>
            <hr/>
            </div>
            <div asp-validation-summary="All"></div>
            <div class="mb-3">
                <label asp-for="ComplaintId"></label>
                <input asp-for="ComplaintId" class="form-control" disabled/>
                 <input asp-for="ComplaintId" class="form-control" hidden/>
                <span asp-validation-for="ComplaintId" class="text-danger"></span>
                <label asp-for="DateOfComplaint"></label>
                <input asp-for="DateOfComplaint" class="form-control"/>
                <span asp-validation-for="DateOfComplaint" class="text-danger"></span>
                <label asp-for="ComplaintGiver"></label>
                <input asp-for="ComplaintGiver" class="form-control"/>
                <span asp-validation-for="ComplaintGiver" class="text-danger"></span>
                <label asp-for="ComplaintTitle"></label>
               <input asp-for="ComplaintTitle" class="form-control" />
               <label asp-for="ComplaintCategory"></label>
                <select asp-for="ComplaintCategory" class="form-control">
                 <option asp-for="ComplaintCategory" value="Water Issue">Water Issue</option>
                 <option asp-for="ComplaintCategory" value="Bore Well Issue">Bore Well Issue</option>
                 <option asp-for="ComplaintCategory" value="Neighbor Issue">Neighbor Issue</option>
                 <option asp-for="ComplaintCategory" value="Electricity Issue">Electricity Issue</option>
                 <option asp-for="ComplaintCategory" value="Lift Issue">Lift Issue</option>
                 <option asp-for="ComplaintCategory" value="Parking Issue">Parking Issue</option>
                 <option asp-for="ComplaintCategory" value="Vehicle Damage Issue">Vehicle Damage Issue</option>
                 <option asp-for="ComplaintCategory" value="Stolen/Theft Issue">Stolen/Theft Issue</option>
                 <option asp-for="ComplaintCategory" value="Noise Issue">Noise Issue</option>
                 <option asp-for="ComplaintCategory" value="Other Issue">Other Issue</option>
                </select>
                <span asp-validation-for="ComplaintCategory" class="text-danger"></span>


                <span asp-validation-for="ComplaintTitle" class="text-danger"></span>
                <label asp-for="ComplaintDetail"></label>
                
                    <textarea asp-for="ComplaintDetail"></textarea>
                    
                <span asp-validation-for="ComplaintDetail" class="text-danger"></span>
               
               
               

            </div>
    
    <button type="submit" class="btn btn-primary" style="width:150px">Edit</button>
    <a asp-controller="Complaint" asp-action="Index" class="btn btn-secondary" style="width:150px">
        Back to list
    </a>
    </div>
</form>
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial"></partial>
    }
}

Views/Complaint/Index.cshtml
@model IEnumerable<Complaint>
@{
    ViewData["Title"] = "Index";

}
<partial name="_Notification"></partial>
<br><br>
<div class="col-12 text-end">
    <a asp-controller="Complaint" asp-action="Create" class="btn btn-primary">
        Register Complaint
    </a>
    </div>
    <br><br>
   
<table class="table table-border table-striped rounded-2" style="width:100%;text-align:center;background-color: rgba(100,100,100, 0.1) !important">
    <thead class="rounded-2">
        <tr>
            <th>
                Complaint Registered By
            </th>
            <th>
                Title
            </th>
        </tr>
    </thead>
    <tbody class="rounded-2">

    
    @foreach(var obj in Model)
    {
       if(obj.DateOfComplaint >= DateTime.Today.AddDays(-30) && obj.DateOfComplaint <= DateTime.Today)
        {
        <tr >
            <td width="50%" hidden>
                @obj.ComplaintId
            </td>
             <td width="50%">
                @obj.ComplaintGiver
            </td>
            <td width="50%">
                @obj.ComplaintTitle
            </td>
             
            <td>
               <div class="m-75 btn-group" role="group">
                    <a asp-controller="Complaint" asp-action="View" asp-route-ComplaintId ="@obj.ComplaintId" class="btn btn-primary">View</a>
                </div>
            </td>
            <td>
                <div class="m-75 btn-group" role="group">
                    <a asp-controller="Complaint" asp-action="Edit" asp-route-ComplaintId ="@obj.ComplaintId" class="btn btn-primary">Edit</a>
                </div>
            </td>
            <td>
                <div class="m-75 btn-group" role="group">
                    <a asp-controller="Complaint" asp-action="Delete" asp-route-ComplaintId ="@obj.ComplaintId" class="btn btn-primary">Delete</a>
                </div>
            </td>
        </tr>
        }
    }
    </tbody>
</table>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.4.0/jspdf.umd.min.js"></script>

Views/Complaint/View.cshtml
@model Complaint

        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <p>
                <strong>Notice ID:</strong> @Model.ComplaintId
            </p>
            
            <p>
                <strong>Complaint Registered Date:</strong> @Model.DateOfComplaint
            </p>
            
            <p>
                <strong>Complaint Registered By:</strong> @Model.ComplaintGiver
            </p>
            
            <h1 style="text-align:center">
                @Model.ComplaintTitle
            </h1>
            <div style="width:500px;height:500px;text-align:center;margin: 0 auto;">
            <p style="text-align:justify;">
                @Html.Raw(Model.ComplaintDetail.Replace("\r\n", "<br />"))
            </p>
            </div>
        </div>
    
        <a asp-controller="Complaint" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to list
        </a>
    </div>


@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial"></partial>
    }
}